[EM]
name = "Encryption Mode"
description = "AES加密模式相关漏洞"
file_extensions = [".py"]
match_method = "regex"
target_patterns = ["AES\\.MODE_\\w+"]
keywords = ["AES", "MODE", "cipher", "encrypt", "decrypt", "key", "block", "mode", "padding", "pem", "rsa", "crypto", "security", "加密", "解密", "密钥", "密码", "模式", "块", "填充", "安全"]

[SSL]
name = "SSL protocol"
description = "SSL版本漏洞"
file_extensions = [".py"]
match_method = "regex"
target_patterns = ["ssl\\.PROTOCOL_\\w+"]
keywords = ["http", "conditions", "server", "tested", "https", "root", "tls", "pyopenssl", "ssl", "configuration", "client", "attack", "certificate", "certificates", "install"]

[PBE]
name = "Password-based encryption"
description = "加密迭代次数漏洞"
file_extensions = [".py"]
match_method = "ast"
target_patterns = ["PBKDF2HMAC\\s*\\((?s:.*?)\\)"]
ast_patterns = ["PBKDF2HMAC"]
keywords = ["Cryptographical", "calculations", "calculate", "decrypte", "decrypting", "cryptor", "Encryption", "Ciphertext", "Encrypts"]

[DEFAULT]
name = "Default"
description = "默认配置"
file_extensions = [".py"]
match_method = "regex"
target_patterns = ["PATTERN_NOT_FOUND"]
keywords = ["default"]